"""prd_0514_schema

Revision ID: a5ee7867b269
Revises: 
Create Date: 2026-05-15 00:13:33.138262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a5ee7867b269'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_profiles',
    sa.Column('customer_id', sa.String(length=128), nullable=False),
    sa.Column('industry', sa.String(length=128), nullable=False),
    sa.Column('market_region', sa.String(length=64), nullable=False),
    sa.Column('product_group', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('sensitive_topics', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('risk_factors', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('indicators',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('country', sa.String(length=32), nullable=True),
    sa.Column('category_big', sa.String(length=32), nullable=True),
    sa.Column('category_mid', sa.String(length=32), nullable=True),
    sa.Column('category_small', sa.String(length=32), nullable=True),
    sa.Column('feature_name', sa.String(length=256), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('cycle', sa.String(length=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feature_name', 'date', 'source', name='uq_indicator_feature_date_source')
    )
    op.create_index(op.f('ix_indicators_date'), 'indicators', ['date'], unique=False)
    op.create_index(op.f('ix_indicators_feature_name'), 'indicators', ['feature_name'], unique=False)
    op.create_table('products',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('key_features', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('key_feature_importance', postgresql.ARRAY(sa.Float()), nullable=False),
    sa.Column('axis', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('trigger_events',
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('feature', sa.String(length=256), nullable=False),
    sa.Column('product_code', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=128), nullable=True),
    sa.Column('change_rate', sa.Float(), nullable=False),
    sa.Column('direction', sa.Enum('UP', 'DOWN', name='event_direction'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_trigger_events_customer_id'), 'trigger_events', ['customer_id'], unique=False)
    op.create_index(op.f('ix_trigger_events_date'), 'trigger_events', ['date'], unique=False)
    op.create_index(op.f('ix_trigger_events_product_code'), 'trigger_events', ['product_code'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('role', sa.Enum('SALES', 'MANAGER', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('assigned_customers',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Enum('PRIMARY', 'SUPPORT', name='assignment_role'), nullable=False),
    sa.Column('assigned_at', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_profiles.customer_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'customer_id')
    )
    op.create_table('org_hierarchy',
    sa.Column('manager_id', sa.String(length=64), nullable=False),
    sa.Column('subordinate_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subordinate_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('manager_id', 'subordinate_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('org_hierarchy')
    op.drop_table('assigned_customers')
    op.drop_table('users')
    op.drop_index(op.f('ix_trigger_events_product_code'), table_name='trigger_events')
    op.drop_index(op.f('ix_trigger_events_date'), table_name='trigger_events')
    op.drop_index(op.f('ix_trigger_events_customer_id'), table_name='trigger_events')
    op.drop_table('trigger_events')
    op.drop_table('products')
    op.drop_index(op.f('ix_indicators_feature_name'), table_name='indicators')
    op.drop_index(op.f('ix_indicators_date'), table_name='indicators')
    op.drop_table('indicators')
    op.drop_table('customer_profiles')
    # ### end Alembic commands ###
