"""prd_0523_users_profile_columns

Revision ID: b618be188309
Revises: d9df9de43878
Create Date: 2026-05-23 17:03:05.288298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b618be188309'
down_revision: Union[str, None] = 'd9df9de43878'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('employee_no', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('department', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    op.drop_column('users', 'department')
    op.drop_column('users', 'employee_no')
    # ### end Alembic commands ###
