"""prd_0516_schema_axis_cycle

Revision ID: d9df9de43878
Revises: a5ee7867b269
Create Date: 2026-05-17 21:12:56.745197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'd9df9de43878'
down_revision: Union[str, None] = 'a5ee7867b269'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('key_feature_cycle', postgresql.ARRAY(sa.String()), nullable=False))
    op.drop_column('products', 'axis')
    op.add_column('users', sa.Column('primary_product_code', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'primary_product_code')
    op.add_column('products', sa.Column('axis', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('products', 'key_feature_cycle')
    # ### end Alembic commands ###
